# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class helloworldStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sayhello = channel.unary_unary(
        '/helloworld_demo.helloworld/sayhello',
        request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
        response_deserializer=helloworld__pb2.HelloReply.FromString,
        )


class helloworldServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sayhello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_helloworldServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sayhello': grpc.unary_unary_rpc_method_handler(
          servicer.sayhello,
          request_deserializer=helloworld__pb2.HelloRequest.FromString,
          response_serializer=helloworld__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld_demo.helloworld', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
