# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mnist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mnist.proto',
  package='mnist',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmnist.proto\x12\x05mnist\"%\n\x13MnistPredictRequest\x12\x0e\n\x06inputs\x18\x01 \x01(\x0c\"<\n\x14MnistPredictResponse\x12\x0f\n\x07outputs\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x32\x63\n\x16MnistPredictionService\x12I\n\x0cMnistPredict\x12\x1a.mnist.MnistPredictRequest\x1a\x1b.mnist.MnistPredictResponse\"\x00\x62\x06proto3')
)




_MNISTPREDICTREQUEST = _descriptor.Descriptor(
  name='MnistPredictRequest',
  full_name='mnist.MnistPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='mnist.MnistPredictRequest.inputs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=59,
)


_MNISTPREDICTRESPONSE = _descriptor.Descriptor(
  name='MnistPredictResponse',
  full_name='mnist.MnistPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='mnist.MnistPredictResponse.outputs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='mnist.MnistPredictResponse.probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['MnistPredictRequest'] = _MNISTPREDICTREQUEST
DESCRIPTOR.message_types_by_name['MnistPredictResponse'] = _MNISTPREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MnistPredictRequest = _reflection.GeneratedProtocolMessageType('MnistPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _MNISTPREDICTREQUEST,
  __module__ = 'mnist_pb2'
  # @@protoc_insertion_point(class_scope:mnist.MnistPredictRequest)
  ))
_sym_db.RegisterMessage(MnistPredictRequest)

MnistPredictResponse = _reflection.GeneratedProtocolMessageType('MnistPredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _MNISTPREDICTRESPONSE,
  __module__ = 'mnist_pb2'
  # @@protoc_insertion_point(class_scope:mnist.MnistPredictResponse)
  ))
_sym_db.RegisterMessage(MnistPredictResponse)



_MNISTPREDICTIONSERVICE = _descriptor.ServiceDescriptor(
  name='MnistPredictionService',
  full_name='mnist.MnistPredictionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=123,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='MnistPredict',
    full_name='mnist.MnistPredictionService.MnistPredict',
    index=0,
    containing_service=None,
    input_type=_MNISTPREDICTREQUEST,
    output_type=_MNISTPREDICTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MNISTPREDICTIONSERVICE)

DESCRIPTOR.services_by_name['MnistPredictionService'] = _MNISTPREDICTIONSERVICE

# @@protoc_insertion_point(module_scope)
